name: cookie_jar
description: A cookie manager for http requests in Dart, help you to deal with the cookie policies and persistence.
version: 5.0.0-dev.1
repository: https://github.com/flutterchina/cookie_jar
issue_tracker: https://github.com/flutterchina/cookie_jar/issues

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  meta: ^1.5.0
  universal_io: ^2.2.0

dev_dependencies:
  lints: any
  test: ^1.16.3
